#!/usr/bin/env bash
# Accepts a string as an argument
# + displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed.
# + ping the IP 5 times

num=$#
if [ $num -eq 0 ]
then
	echo "Usage: $(basename $0) {IP_ADDRESS}"
	exit -1
fi
ping -c 5 "${1}"
