#!/usr/bin/env bash
#prints Best School 10 times but for the 9th iteration, displays Best School and then Hi

i=1
while [ $i -lt 11 ]
do
	echo "Best School"
	if [ $i -eq 9 ]
		then
			echo "Hi"
		fi
	(( i++ ))
done
