#!/usr/bin/env bash
#script that loops from 1 to 10

i=1
while [ $i -lt 9 ]
do
	echo "Best School"

	if [ $i -eq 3 ]
	then
		echo "bad luck"

	elif [ $i -eq 6 ]
	then
		echo "good luck"
	fi
	(( i++ ))

done
